name: Leitura Biblica Diaria

on:
  schedule:
    - cron: "0 9 * * *"
    - cron: "5 9 * * *"   # 06:05 Fortaleza
    - cron: "10 9 * * *"  # 06:10 Fortaleza
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Rodar bot
        env:
          PLAN_CSV: plan.csv
          BIBLE_VERSION: nvi
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}
        run: python bot.py

